### ISSUE TITLE
Versioning of the protocol-required database types

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1552]
# Overview

In order to support upgrades, database types must support seamless versioning. For example, we must support the ability to change the key type and/or value type of a given table while maintaining backwards compatibility with existing data.

Database tables:
- [x] Coins (https://github.com/FuelLabs/fuel-core/pull/1628)
  - Value: `CompressedCoin`
- [x] ~~ContractsAssets~~ Note: `ContractsAssets::Value` will always be a `Word`
  - ~~Value: `Word`~~
- [x] ~~ContractsAssetsMerkleData~~ Note: `sparse::Primitive` does not need to be versioned 
  - ~~Value: `fuel_merkle::sparse::Primitive`~~ 
- [x] ContractsAssetsMerkleMetadata (https://github.com/FuelLabs/fuel-core/pull/1639)
  - Value: `SparseMerkleMetadata`
- [x] ContractsInfo (https://github.com/FuelLabs/fuel-vm/pull/673)
  - Value: `(Salt, Bytes32)` 
- [x] ContractsLatestUtxo (https://github.com/FuelLabs/fuel-core/pull/1712)
  - Value: `ContractUtxoInfo`
- [x] ~~ContractsRawCode~~ Note: `ContractsRawCode::Value` will always be a `[u8]`
  - ~~Value: `[u8]` (write)~~
  - ~~OwnedValue: `Contract` (read)~~
- [x] [ContractsState](https://github.com/FuelLabs/fuel-vm/issues/655 ) (https://github.com/FuelLabs/fuel-vm/pull/671)
  - Value: `Bytes32`
- [x] ~~ContractsStateMerkleData~~ Note: `sparse::Primitive` does not need to be versioned 
  - ~~Value: `fuel_merkle::sparse::Primitive`~~
- [x] ContractsStateMerkleMetadata (https://github.com/FuelLabs/fuel-core/pull/1639)
  - Value: `SparseMerkleMetadata`
- [x] ~~FuelBlockMerkleData~~  Note: `binary::Primitive` does not need to be versioned 
  - ~~Value: `fuel_merkle::binary::Primitive`~~
- [x] FuelBlockMerkleMetadata (https://github.com/FuelLabs/fuel-core/pull/1639)
  - Value: `DenseMerkleMetadata`
- [x] FuelBlocks (https://github.com/FuelLabs/fuel-core/pull/1593)
  - Value: `CompressedBlock`
- [x] Messages (https://github.com/FuelLabs/fuel-core/pull/1632)
  - Value: `Message`
- [x] ProcessedTransactions
  - Value: `()`
- [x] SpentMessages
  - Value: `()`
- [x] Transactions
  - Value: `Transaction`

# Implementation

For each database type:
- ~~Make `Mappable::Key` versionable~~
- Make `Mappable::Value` versionable

Use `non_exhaustive` for enums.

Note: Double-check that we spend one byte to store discriminant of the enum
