### ISSUE TITLE
E2E testing of regenesis

### ISSUE THREAD

**Issue by segfault-magnet** [FuelLabs/fuel-core#1756]
High level tracking for regenesis testing:

- [x] E2E framework for regenesis testing: https://github.com/FuelLabs/fuel-core/issues/1766
- [x] E2E tests for on-chain data: https://github.com/FuelLabs/fuel-core/issues/1763
- [x] E2E tests for off-chain data: https://github.com/FuelLabs/fuel-core/issues/1764
- [ ] Performance tests: https://github.com/FuelLabs/fuel-core/issues/1765
- [ ] Stress tests: https://github.com/FuelLabs/fuel-core/issues/1571

**Comment by Bamiboygraphics** [comment]
Good, Thanks for this.

**Comment by xgreenx** [comment]
The main testing part is done. Remains stress testing of the regenesis. The main tests are also done, but regenesis itself is slow, so we need to investigate why and speed up it.
