### ISSUE TITLE
Integration test for nodes running on different versions of `/fuel/req_res` protocol

### ISSUE THREAD

**Issue by acerone85** [FuelLabs/fuel-core#2374]
Follow-up from #2362 

Context: 

After #2362 we have two versions of the `/fuel/req_res` protocol. Both protocols use the same type for requests, but differ on the type of responses.
* `/fuel/req_res/0.0.1`: nodes can send an empty (`None`) response when they cannot fulfill a request incoming from a remote peer, 
* `/fuel/req_res/0.0.2`: nodes send an error response with an error code when they cannot fulfill a request incoming from a remote peer. A special error code `0: V1ProtocolEmptyResponse` is reserved for dealing with empty responses coming from peers using version `0.0.1` of the protocol, and used at a higher level.

The `request_response` behaviour implementing these two protocols guarantees backwards-compatibility among fuel-core nodes running different version of the protocol. In particular, the following should hold: 
* Nodes both supporting version `0.0.2` of the protocol should communicate using this version, 
* A node supporting both versions `0.0.1` and `0.0.2` of the protocol can send requests to a node supporting only version `0.0.1` of the protocol using this version. However, `Empty` responses received by this peer will automatically be converted to a response with error code `0: V1ProtocolEmptyResponse`. 
* A node supporting both version `0.0.1` and `0.0.2` of the protocol can send responses to requests made by a node that supports version `0.0.1`, using that version. In this case, any error response is automatically converted to an empty  response.

# Task: 

Implement different integration tests that check the behaviour above. 
- [ ] Nodes supporting `/fuel/req_res/0.0.2` communicate using that version of the protocol, 
- [ ] A node supporting `/fuel/req_res/0.0.1` can answer requests from nodes supporting both `/fuel/req_res/0.0.1` and `/fuel/req_res/0.0.2`, 
- [ ] A node supporting `/fuel/req_res/0.0.1` can send request to nodes supporting both `/fuel/req_res/0.0.1` and `/fuel/req_res/0.0.2` and receive a response back

It might be best implementing these as backward compatibility tests, using both a new and older version of the node

# Acceptance criteria: 

- [ ] Integration tests mentioned above are implemented, executed in the CI checks and pass

# Relevant files: 
* Definition of request and response messages: https://github.com/FuelLabs/fuel-core/blob/1311-return-better-error-messages-from-p2p-requests/crates/services/p2p/src/request_response/messages.rs
* Implementation of codec trait and protocols required by the request response protocol: https://github.com/FuelLabs/fuel-core/blob/1311-return-better-error-messages-from-p2p-requests/crates/services/p2p/src/codecs/postcard.rs
* (might be useful): Place where protocols exchanged with remote peers can be retrieved in our codebase: https://github.com/FuelLabs/fuel-core/blob/b2b5b3cb6040b732eec70f0f3d5a24e77bb1110b/crates/services/p2p/src/peer_manager.rs#L133
